# Site settings
title: mjzitek.github.io
email: mzitek@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm using this for documentation on a few of my projects
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mjzitek.github.io" # the base hostname & protocol for your site
twitter_username: mjzitek
github_username:  mjzitek

# Build settings
markdown: kramdown
